name: today
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  audio_video_progress_bar: ^0.11.0
  # audioplayers: ^3.0.1
  audioplayers: ^5.2.0
  cached_network_image: ^3.2.3
  chewie: ^1.4.0
  cloud_firestore: ^4.3.0
  cupertino_icons: ^1.0.2
  custom_pop_up_menu: null
  file_picker: ^5.2.4
  filesystem_picker: ^3.1.0
  firebase_auth: ^4.2.3
  firebase_core: ^2.4.0
  firebase_storage: ^11.0.9
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_spinkit: ^5.1.0
  get: ^4.6.5
  # image_picker: ^0.8.7+2
  intl: null
  just_audio: ^0.9.30
  oktoast: null
  on_audio_query: ^2.6.1
  path_provider: ^2.0.11
  permission_handler: ^10.2.0
  photo_manager: null
  provider: null
  shared_preferences: ^2.0.20
  splash_screen_view: null
  video_box: ^0.17.0
  video_player: ^2.4.10
  video_thumbnail: ^0.5.3
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware
# For details regarding adding assets from package dependencies, see
# https://flutter.dev/assets-and-images/#from-packages
# To add custom fonts to your application, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
fonts:
  - family: RobotoSlab
    fonts:
      - asset: fonts/RobotoSlab-Regular.ttf
flutter_intl:
  enabled: true

#      - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts from package dependencies,
# see https://flutter.dev/custom-fonts/#from-packages
